Add content to inspector
multiformats/cid-utils-website pull request #50
Opened 2022-08-05 15:47 UTC by DannyS03

Adds complementary technical content to multiformats throughout the inspector. Think it is reasonable to say that the inspector can generally be updated with enhanced UI/UX

cc. @lidel

2022-08-05 20:49 UTC, lidel requested changes
Thanks!  This needs some UX  / devrel  :eyes:  


- Before: https://cid.ipfs.tech/#QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR
- This PR:  https://bafybeiekwowj7jkbguo77nf2tkqh76jkmnjyblwvyecn57tv6p6hcrcg3q.on.fleek.co/#QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR

@juliaxbow  @2color will you have time to provide feedback on this?

2022-08-05 20:49 UTC, lidel commented on index.html
> +        </br> binary: cid_version - multicodec - multihash
I think i know what you wanted to convey here, but description does not look intuitive. Perhaps human sentence is better here?

```suggestion
        </br>CID is encoded as String using Multibase.
        </br>After decoding Multibase, the remaining value is bytes. 
```

2022-08-05 20:49 UTC, lidel commented on index.html
> +       </br>data in a variety of base-encoding formats.
nit: we use "data model" only in context of https://ipld.io
https://docs.ipfs.tech/concepts/glossary/#multibase is a protocol for encoding stuff:
```suggestion
       </br>Self-describing protocol for expressing raw binary
       </br>data in a variety of base-encoding formats.
```

2022-08-05 22:34 UTC, juliaxbow commented
Sure, will take a look and suggest a few changes. Some initial thoughts in the interim:

- Information hierarchy 
    - Unclear what is most important; hard to quickly find sections 
- Links
    - Links all take different formats; unclear what I can click or not
- Informational text
    - Great to link out to documentation but could be helpful to have more details on the page (or maybe once the link issue is fixed this won’t be as big of an issue)
    - The info text that exists is hard to differentiate from other content because of font choices

2022-08-08 05:26 UTC, juliaxbow commented
Made some light suggestions for changes that should make this more readable to the average viewer without overhauling the page in its entirety, though if that's what you're looking for please let me know.

Update:
![CID Inspector (recommendations)](https://user-images.githubusercontent.com/58958327/183345227-b8d14d8d-b04a-4f94-b955-d0636cc86e54.png)

With comments:
![CID Inspector (marked up)](https://user-images.githubusercontent.com/58958327/183345226-8cc4d17e-5c28-4cdc-80ab-edab6249b44f.png)

(poor quality) gif showing highlight on hover & link->section for CID components 
![CID_explorer](https://user-images.githubusercontent.com/58958327/183345254-0d501795-4543-4d6b-9328-60733f2326d7.gif)

2022-08-08 06:42 UTC, DannyS03 commented
> Made some light suggestions for changes that should make this more readable to the average viewer without overhauling the page in its entirety, though if that's what you're looking for please let me know.
> 
> Update: ![CID Inspector (recommendations)](https://user-images.githubusercontent.com/58958327/183345227-b8d14d8d-b04a-4f94-b955-d0636cc86e54.png)
> 
> With comments: ![CID Inspector (marked up)](https://user-images.githubusercontent.com/58958327/183345226-8cc4d17e-5c28-4cdc-80ab-edab6249b44f.png)
> 
> (poor quality) gif showing highlight on hover & link->section for CID components ![CID_explorer](https://user-images.githubusercontent.com/58958327/183345254-0d501795-4543-4d6b-9328-60733f2326d7.gif) [ ![CID_explorer](https://user-images.githubusercontent.com/58958327/183345254-0d501795-4543-4d6b-9328-60733f2326d7.gif) ](https://user-images.githubusercontent.com/58958327/183345254-0d501795-4543-4d6b-9328-60733f2326d7.gif) [ ](https://user-images.githubusercontent.com/58958327/183345254-0d501795-4543-4d6b-9328-60733f2326d7.gif)

This is great

2022-08-09 09:43 UTC, hacdias commented
I think there is a lot to unpack on this PR, as well as with the UX improvement suggestions.

**1)** I made some updates to the header based on @juliaxbow's suggestions. You can see the results here:

- https://bafybeiah2naqoecumkw3hsedru27oqr266k2sbaf7nc5xfk36sh4wumfpy.on.fleek.co/#QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR

@juliaxbow we have this thing (https://github.com/ipfs-shipyard/ipfs-css) with colors and some CSS that we use across different projects, including this one. I've applied your suggestions using the colors from `ipfs-css` and [`tachyons`](https://tachyons.io/).

**2)** I personally don't like the way this information is displayed with the `>`. I think that we should either have a link for the documentation for more in-depth details, or have a [folding thing](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) with the information inside. 

![image](https://user-images.githubusercontent.com/5447088/183612220-552abd1d-cd1e-420a-9de4-4de24775f405.png)

Or maybe a "?" icon that, when pressed, shows more information.

Depending on how we solve this textual issue, we may, or may not, need the boxes around each zone because there wouldn't be that much information.

What do you all think?

2022-08-09 09:44 UTC, hacdias reviewed
I think there is a lot to unpack on this PR, as well as with the UX improvement suggestions.

**1)** I made some updates to the header based on @juliaxbow's suggestions. You can see the results here:

- https://bafybeiah2naqoecumkw3hsedru27oqr266k2sbaf7nc5xfk36sh4wumfpy.on.fleek.co/#QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR

@juliaxbow we have this thing (https://github.com/ipfs-shipyard/ipfs-css) with colors and some CSS that we use across different projects, including this one. I've applied your suggestions using the colors from `ipfs-css` and [`tachyons`](https://tachyons.io/).

**2)** I personally don't like the way this information is displayed with the `>`. I think that we should either have a link for the documentation for more in-depth details, or have a [folding thing](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) with the information inside. 

![image](https://user-images.githubusercontent.com/5447088/183612220-552abd1d-cd1e-420a-9de4-4de24775f405.png)

Or maybe a "?" icon that, when pressed, shows more information.

Depending on how we solve this textual issue, we may, or may not, need the boxes around each zone because there wouldn't be that much information.

What do you all think?

2023-11-03 22:58 UTC, closed without merging